/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-mikes_oot
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_MIKES_OOT_API_H
#define INCLUDED_MIKES_OOT_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_mikes_oot_EXPORTS
#define MIKES_OOT_API __GR_ATTR_EXPORT
#else
#define MIKES_OOT_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_MIKES_OOT_API_H */
