/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(double_to_float_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5872250d344c368ac726fe778bf5faba)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mikes_oot/double_to_float_stream.h>
// pydoc.h is automatically generated in the build directory
#include <double_to_float_stream_pydoc.h>

void bind_double_to_float_stream(py::module& m)
{

    using double_to_float_stream    = ::gr::mikes_oot::double_to_float_stream;


    py::class_<double_to_float_stream, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<double_to_float_stream>>(m, "double_to_float_stream", D(double_to_float_stream))

        .def(py::init(&double_to_float_stream::make),
           D(double_to_float_stream,make)
        )
        



        ;




}








