/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(float_to_double_stream.h) */
/* BINDTOOL_HEADER_FILE_HASH(01a609f6835ef2f50c871938a6f7514d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mikes_oot/float_to_double_stream.h>
// pydoc.h is automatically generated in the build directory
#include <float_to_double_stream_pydoc.h>

void bind_float_to_double_stream(py::module& m)
{

    using float_to_double_stream = ::gr::mikes_oot::float_to_double_stream;


    py::class_<float_to_double_stream,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<float_to_double_stream>>(
        m, "float_to_double_stream", D(float_to_double_stream))

        .def(py::init(&float_to_double_stream::make), D(float_to_double_stream, make))


        ;
}
