/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pub_sink_64bit.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3f092f37b0f405a392fba79b8864e04c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mikes_oot/pub_sink_64bit.h>
// pydoc.h is automatically generated in the build directory
#include <pub_sink_64bit_pydoc.h>

void bind_pub_sink_64bit(py::module& m)
{

    using pub_sink_64bit = ::gr::mikes_oot::pub_sink_64bit;


    py::class_<pub_sink_64bit,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pub_sink_64bit>>(m, "pub_sink_64bit", D(pub_sink_64bit))

        .def(py::init(&pub_sink_64bit::make),
             py::arg("itemsize"),
             py::arg("vlen"),
             py::arg("address"),
             py::arg("timeout") = 100,
             py::arg("pass_tags") = false,
             py::arg("hwm") = -1,
             py::arg("key") = "",
             py::arg("drop_on_hwm") = true,
             D(pub_sink_64bit, make))


        .def("last_endpoint",
             &pub_sink_64bit::last_endpoint,
             D(pub_sink_64bit, last_endpoint))

        ;
}
