/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(stream_to_vector_64bit.h) */
/* BINDTOOL_HEADER_FILE_HASH(81f794722ca07e3f7e7828439de40221)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mikes_oot/stream_to_vector_64bit.h>
// pydoc.h is automatically generated in the build directory
#include <stream_to_vector_64bit_pydoc.h>

void bind_stream_to_vector_64bit(py::module& m)
{

    using stream_to_vector_64bit = ::gr::mikes_oot::stream_to_vector_64bit;


    py::class_<stream_to_vector_64bit,
               gr::sync_decimator,
               std::shared_ptr<stream_to_vector_64bit>>(
        m, "stream_to_vector_64bit", D(stream_to_vector_64bit))

        .def(py::init(&stream_to_vector_64bit::make),
             py::arg("itemsize"),
             py::arg("nitems_per_block"),
             D(stream_to_vector_64bit, make))


        ;
}
